info:
  component: Turbine

PREFIX:
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

server:
  port: ${PORT:8989}

management:
  port: 8990


eureka:
  instance:
      metadataMap:
          instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
      serviceUrl:
          defaultZone: http://127.0.0.1:8761/eureka/

---
spring:
  profiles: cloud
management:
  port: -1
