server:
  port: 0

spring:
  oauth2:
    resource:
      userInfoUri: http://localhost:9999/uaa/user

management:
  security:
    enabled: false

eureka:
  instance:
      metadataMap:
          instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
      serviceUrl:
          defaultZone: http://127.0.0.1:8761/eureka/